# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Rituraj Tripathi
# Description of the Site
description: Turning pixels into experiences, I’m a frontend developer passionate about creating web interfaces that are both intuitive and engaging. I focus on crafting clean, responsive designs that not only look great but feel natural to use. Whether I’m building something new or improving an existing project, I’m all about those small details that make a big difference
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Rituraj, Tripathi, Rituraj Tripathi, Frontend Developer, Satna, Madhya Pradesh
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: riturajtripathi139@gmail.com
facebook_username: rituraj.tripathi.10
twitter_username: Rituraj9738
instagram_username: riturajtripathi139
linkedin_username: riturajtripathi
github_username:  riturajtripathi139
youtube_channel_id: /
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics:

# Disqus
disqus-shortname: 

# Name of the Author
author-name: RITURAJ TRIPATHI
# URL for the Image of the Author
author-image: https://github.com/riturajtripathi139.png
# 60 Words About the Author
author-about: Turning pixels into experiences, I’m a frontend developer passionate about creating web interfaces that are both intuitive and engaging. I focus on crafting clean, responsive designs that not only look great but feel natural to use. Whether I’m building something new or improving an existing project, I’m all about those small details that make a big difference
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/riturajtripathi

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
